language: cpp

before_install:
  - sudo apt-get install -y libboost-all-dev python-pytest liblog4cpp5-dev

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test && make doc
