language: cpp

before_install:
  - sudo apt-get install -y libboost-all-dev

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test && make doc
